# coding: utf-8

"""
    Cortex Agent REST API

    OpenAPI 3.1 specification for the Cortex Agent REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@snowflake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ChartEventData(BaseModel):
    """
    ChartEventData
    """ # noqa: E501
    content_index: StrictInt = Field(description="The index in the response content array this event represents")
    tool_use_id: StrictStr = Field(description="The ID of the tool use that generated this chart")
    chart_spec: StrictStr = Field(description="The vega-lite chart specification serialized as a string")
    analyst_tool_use_id: Optional[StrictStr] = Field(default=None, description="The tool use id of the Cortex Analyst tool call that generated the data for this chart. This is deprecated. Clients should use `tool_use_id` to fetch the chart tool use and from there find the Analyst tool use id if needed.")
    __properties: ClassVar[List[str]] = ["content_index", "tool_use_id", "chart_spec", "analyst_tool_use_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChartEventData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChartEventData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "content_index": obj.get("content_index"),
            "tool_use_id": obj.get("tool_use_id"),
            "chart_spec": obj.get("chart_spec"),
            "analyst_tool_use_id": obj.get("analyst_tool_use_id")
        })
        return _obj


