# coding: utf-8

"""
    Cortex Agent REST API

    OpenAPI 3.1 specification for the Cortex Agent REST API

    The version of the OpenAPI document: 1.0.0
    Contact: support@snowflake.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SearchResource(BaseModel):
    """
    Configuration for search functionality. Defines how document search and retrieval should be performed. 
    """ # noqa: E501
    search_service: Optional[StrictStr] = Field(default=None, description="The name of the search service. Must in format: database.schema.service_name ")
    name: Optional[StrictStr] = Field(default=None, description="reserved")
    max_results: Optional[StrictInt] = Field(default=None, description="The number of search results used in LLM prompt. ")
    title_column: Optional[StrictStr] = Field(default=None, description="The title column of the document. ")
    id_column: Optional[StrictStr] = Field(default=None, description="The ID column of the document. ")
    filter: Optional[Dict[str, Any]] = Field(default=None, description="Filter query for search results. ")
    experimental: Optional[Dict[str, Any]] = Field(default=None, description="reserved")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["search_service", "name", "max_results", "title_column", "id_column", "filter", "experimental"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "search_service": obj.get("search_service"),
            "name": obj.get("name"),
            "max_results": obj.get("max_results"),
            "title_column": obj.get("title_column"),
            "id_column": obj.get("id_column"),
            "filter": obj.get("filter"),
            "experimental": obj.get("experimental")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


